console.log('Testing for isPhone function:')

console.log('Testing phone number format XXXXXXXXXX')
console.log('expected output: true')
console.log(isPhone('9789904992'))

console.log('Testing phone number format XXXXXXXXXX with a non number at the beginning')
console.log('expected output: false')
console.log(isPhone('o98403330293'))
console.log('Testing phone number format XXXXXXXXXX with a non number trailing')
console.log('expected output: fasle')
console.log(isPhone('98403330293a'))
console.log('Testing phone number format XXXXXXXXXX with a non number in the middle')
console.log('expected output: false')
console.log(isPhone('98403df330293'))
console.log('Testing phone number format XXXXXXXXXX with a number in the beginning, middle and end')
console.log('expected output: true')
console.log(isPhone('o984a03330293p'))
console.log('Testing phone number format XXXXXXXXXX with extra numbers at the beginning and end')
console.log('expected output: false')
console.log(isPhone('998403330293'))
console.log('Testing phone number format XXXXXXXXXX with extra numbers')
console.log('expected output: false')
console.log(isPhone('984033302930'))

console.log('Testing phone number format XXX XXX XXXX')
console.log('expected output: true')
console.log(isPhone('978 990 4992'))

console.log('Testing phone number format XXX XXX XXXX with a non number trailing')
console.log('expected output: false')
console.log(isPhone('930 823 0394a'))
console.log('Testing phone number format XXX XXX XXXX with a non number at the beginning')
console.log('expected output: false')
console.log(isPhone('a984 033 30293'))
console.log('Testing phone number format XXX XXX XXXX with a non number in the middle')
console.log('expected output: false')
console.log(isPhone('984 03d3 30293'))
console.log('Testing phone number format XXX XXX XXXX with a non number at the beginning, middle and end')
console.log('expected output: false')
console.log(isPhone('o984 a033 30293p'))
console.log('Testing phone number format XXX XXX XXXX with extra numbers at the end')
console.log('expected output: false')
console.log(isPhone('998 403 330293'))
console.log('Testing phone number format XXX XXX XXXX with extra numbers at the beginning and end')
console.log('expected output: false')
console.log(isPhone('9840 333 02930'))
console.log('Testing phone number format XXX XXX XXXX with no first space')
console.log('expected output: false')
console.log(isPhone('984033 0290'))
console.log('Testing phone number format XXX XXX XXXX with no second space')
console.log('expected output: false')
console.log(isPhone('984033 0290'))

console.log('Testing phone number format (XXX) XXX-XXXX')
console.log('expected output: true')
console.log(isPhone('(978) 990-4992'))

console.log('Testing phone number format (XXX) XXX-XXXX with a non number trailing')
console.log('expected output: false')
console.log(isPhone('(978) 990-4992a'))
console.log('Testing phone number format (XXX) XXX-XXXX with a non number at the beginning')
console.log('expected output: false')
console.log(isPhone('a(978) 990-4992'))
console.log('Testing phone number format (XXX) XXX-XXXX with a non number in the middle')
console.log('expected output: false')
console.log(isPhone('(978) 9a90-4992'))
console.log('Testing phone number format (XXX) XXX-XXXX with a non number in the beginning, middle and end')
console.log('expected output: false')
console.log(isPhone('(9a78) 99d0-4992s'))
console.log('Testing phone number format (XXX) XXX-XXXX with no second parenthesis')
console.log('expected output: false')
console.log(isPhone('(978 990-4992'))
console.log('Testing phone number format (XXX) XXX-XXXX with no first parenthesis')
console.log('expected output: false')
console.log(isPhone('978) 990-4992'))
console.log('Testing phone number format (XXX) XXX-XXXX with no -')
console.log('expected output: false')
console.log(isPhone('(978) 9904992'))
console.log('Testing phone number format (XXX) XXX-XXXX with a extra number in the parenthesis')
console.log('expected output: false')
console.log(isPhone('(0978) 990-4992'))
console.log('Testing phone number format (XXX) XXX-XXXX with an extra number at the beginning')
console.log('expected output: false')
console.log(isPhone('0(978) 990-4992'))

console.log('Testing phone number format XXX-XXX-XXXX')
console.log('Expected output: true')
console.log(isPhone('989-293-9999'))

console.log('Testing phone number format XXX-XXX-XXXX with an extra -')
console.log('Expected output is: false')
console.log(isPhone('989--293-9999'))
console.log('Testing phone number format XXX-XXX-XXXX with an extra -')
console.log('Expected output is: false')
console.log(isPhone('989-293--9999'))
console.log('Testing phone number format XXX-XXX-XXXX with 2 extra -')
console.log('Expected output is: false')
console.log(isPhone('989--293--9999'))
console.log('Testing phone number format XXX-XXX-XXXX with a non number trailing')
console.log('Expected output is: false')
console.log(isPhone('989-293-9999a'))
console.log('Testing phone number format XXX-XXX-XXXX with a non number at the beginning')
console.log('Expected output is: false')
console.log(isPhone('a989-293-9999'))
console.log('Testing phone number format XXX-XXX-XXXX with a non number in the middle')
console.log('Expected output is: false')
console.log(isPhone('989-29a3-9999'))
console.log('Testing phone number format XXX-XXX-XXXX with an extra number at the beginning')
console.log('Expected output is: false')
console.log(isPhone('0989-293-9999'))
console.log('Testing phone number format XXX-XXX-XXXX with an extra number at trailing')
console.log('Expected output is: false')
console.log(isPhone('989-293-99989'))
console.log('Testing phone number format XXX-XXX-XXXX with an extra number in the middle')
console.log('Expected output is: false')
console.log(isPhone('989-2993-9999'))

console.log('Testing phone number format (XXX)XXX-XXXX')
console.log('Expected output: true')
console.log(isPhone('(989)293-9999'))

console.log('Testing phone format: (XXX)XXX-XXXX with an extra -')
console.log('expected output: false')
console.log(isPhone('(989)293--9999'))
console.log('Testing phone format: (XXX)XXX-XXXX with an extra paranthesis')
console.log('expected output: false')
console.log(isPhone('(989))293-9999'))
console.log('Testing phone format: (XXX)XXX-XXXX with an extra paranthesis')
console.log('expected output: false')
console.log(isPhone('((989)293-9999'))
console.log('Testing phone format: (XXX)XXX-XXXX with 2 extra paranthesis')
console.log('expected output: false')
console.log(isPhone('((989))293-9999'))
console.log('Testing phone format: (XXX)XXX-XXXX with a trailing non number')
console.log('expected output: false')
console.log(isPhone('(989)293-9999a'))
console.log('Testing phone format: (XXX)XXX-XXXX with a non number before the paranthesis')
console.log('expected output: false')
console.log(isPhone('e(989)293-9999'))
console.log('Testing phone format: (XXX)XXX-XXXX with a non number in the middle')
console.log('expected output: false')
console.log(isPhone('(989)29a3-9999'))
